# Generated by Django 5.0.4 on 2024-04-20 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgebraicOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('PL', 'dodawanie'), ('MN', 'odejmowanie'), ('ML', 'mnożenie'), ('DV', 'dzielenie')], default='ML', max_length=2)),
                ('digits', models.IntegerField(default=1)),
                ('negative_input', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('days_streak', models.IntegerField(default=0)),
                ('questions_streak', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(null=True)),
                ('questions_solved', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
