# Generated by Django 5.0.4 on 2024-04-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contar', '0003_alter_algebraicproblem_latex_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algebraicproblem',
            name='latex_string',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='algebraicproblem',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
